# Generated by Django 5.0.6 on 2024-06-26 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_admin_remove_message_sender_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 22, 8, 13, 842728)),
        ),
    ]
