# Generated by Django 5.0.6 on 2024-06-26 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
