# Generated by Django 5.0.6 on 2024-07-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='title',
        ),
    ]
