# Generated by Django 5.0.6 on 2024-08-02 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_name_chat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('image', models.ImageField(null=True, upload_to='attachments/images/')),
                ('file', models.ImageField(null=True, upload_to='attachments/files/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.message')),
            ],
        ),
    ]
