# Generated by Django 5.0.6 on 2024-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(null=True, upload_to='attachments/files/'),
        ),
    ]
