# Generated by Django 5.0.6 on 2024-06-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(max_length=52, primary_key=True, serialize=False, unique=True),
        ),
    ]
